config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "vehicles#search"
  
  resources :lists, only: [:index, :create]
  resources :payments, only: [:new, :create]
  get 'payment_success', to: 'payments#create', as: 'payment_success'
  get 'payment_cancel', to: 'payments#new', as: 'payment_cancel'

  
  resources :vehicles do 
    resources :steps, only: [:show, :update], controller: 'vehicle/steps'
    collection do
      get 'search'
    end
    member do
      put 'close'
      get 'payment'
      post 'process_payment'
      
    end
  end

  resources :favourites, only: [:index, :create, :destroy] do
    member do
      post 'add_to_favorites'
      delete 'remove_from_favorites'
    end
  end

  namespace :api do
    post :auth, to: "authentication#create"
    delete :auth, to: "authentication#destroy"
    resources :vehicles do 
      resources :steps, only: [:show, :update], controller: 'vehicle/steps'
      collection do
        get 'search'
      end                                                                 
      member do
        put 'close'
      end
    end
  
    resources :favourites, only: [:index, :create, :destroy] do
      member do
        post 'add_to_favorites'
        delete 'remove_from_favorites'
      end
    end
    
  end

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  include PgSearch::Model

  enum city: {
    rawalpindi: 'rawalpindi',
    lahore: 'lahore',
    quetta: 'quetta',
    karachi: 'karachi',
    peshawar: 'peshawar',
    islamabad: 'islamabad'
  }
  enum carModel: {
    suzuki: 'suzuki',
    toyota: 'toyota',
    honda: 'honda',
    bmw: 'bmv'
  }
 
  enum engineType: {
    petrol: 'petrol',
    diesel: 'diesel',
    hybrid: 'hybrid'
  }
  enum color: {
    black: 'black',
    white: 'white',
    gray: 'gray',
    silver: 'silver',
    red: 'red'
  }
  enum assemblyType: {
    local: 'local',
    imported: 'imported'
  }
  enum status: {
    open: 0,
    close: 1
  }

  belongs_to :user
  has_many_attached :vehicle_image

  multisearchable against: [:carModel, :city, :price, :engineType, :transmissonType, :color, :mileage, :engineCapicity, :assemblyType]


  attr_accessor :form_step

  cattr_accessor :form_steps do
  	%w(step1 step2 step3) 
  end
  def required_for_step?(step)
    return true if form_step.nil?
  
    return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
  end
  validates :city, :carModel, :engineType, :color, :assemblyType, :mileage, :price, :description, :transmissonType, :engineCapicity, presence: true,
  if: -> { required_for_step?(:step1) }

  validates :primaryContact, :secondaryContact, presence: true,
  if: -> { required_for_step?(:step2) }

  validates :vehicle_image, presence: true,
  if: -> { required_for_step?(:step3) }

  def self.search_results(query_params)
    if query_params.present?
      searchable_ids = PgSearch.multisearch(query_params.values.reject(&:blank?)).pluck(:searchable_id)
      where(id: searchable_ids, status: 'open')
    else
      open.where.not(primaryContact: nil)
    end
  end

  def self.user_ads(user)
    where(user: user).where.not(primaryContact: nil)
  end

  
end

app/controllers/api/vehicles_controller.rb
class Api::VehiclesController < Api::ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy, :close]
  before_action :authenticate_user!, except: [:search]
  before_action :set_current_user, only: [:new, :create]
  before_action :new_vehicle, only: [:new, :create]


  def index
     @vehicles = Vehicle.user_ads(current_user)
    render json: @vehicles
  end

  def show
    render json: @vehicle
  end

  def new
    render json: @vehicle
  end

  def create
    @vehicle = @user.vehicles.new(vehicle_params)
  
    if @vehicle.save
      render json: { message: 'Vehicle created successfully', vehicle: @vehicle }, status: :created
    else
      render json: { error: 'Failed to create vehicle', errors: @vehicle.errors.full_messages }, status: :unprocessable_entity
    end
  end
  

  def edit
    render json: @vehicle
  end

  def update
    if @vehicle.update(vehicle_params)
      render json: { message: 'Vehicle updated successfully', vehicle: @vehicle }
    else
      render json: { error: 'Failed to update vehicle', errors: @vehicle.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    return unless Favorite.where(vehicle_id: @vehicle.id).destroy_all && @vehicle.destroy

    render json: { message: 'Vehicle destroyed successfully' }
  end

  def search
    @results = Vehicle.search_results(params[:query_params])
    render json: @results
  end

  def close
    debugger
    @vehicle.update(status: 'close')
    render json: { message: 'Vehicle status has been set to close', vehicle: @vehicle }
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def set_current_user 
    @user = current_user
  end 

  def new_vehicle 
    @vehicle = @user.vehicles.new
  end

  def vehicle_params
    params.require(:vehicle).permit(
      :city,
      :mileage,
      :carModel,
      :price,
      :engineType,
      :transmissonType, 
      :engineCapicity, 
      :color, 
      :assemblyType, 
      :description, 
      :primaryContact, 
      :secondaryContact,
      :status,
      vehicle_image: []
    )
  end

end

app/controllers/vehicle/steps_controller.rb
class Vehicle::StepsController < ApplicationController
  include Wicked::Wizard
  before_action :authenticate_user!
  before_action :find_vehicle, only: [:show, :update]
  before_action :validate_user, only: [:show, :update]


  steps *Vehicle.form_steps

  def show
    render_wizard
  end

  def update
    @vehicle.update(vehicle_params(step))
    render_wizard @vehicle
  end

  private

  def find_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def validate_user
    @authorized = current_user.id == @vehicle.user_id
    redirect_to root_path, notice: "Not Authorized" unless @authorized
  end

  def vehicle_params(step)
  	permitted_attributes = case step
  	  when "step1"
  	    [:city, :mileage, :carModel, :price,:engineType, :transmissonType, :engineCapicity, :color, :assemblyType, :description]
  	  when "step2"
  	    [:primaryContact, :secondaryContact]
      when "step3"
        [:vehicle_image =>[]]
  
  	  end

  	params.require(:vehicle).permit(permitted_attributes).merge(form_step: step)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy, :close]
  before_action :authenticate_user!, except: [:search]
  before_action :set_current_user, only:[:new, :create]
  before_action :new_vehicle, only:[:new, :create ]
  
  def index
   @pagy, @vehicles = pagy(Vehicle.user_ads(current_user), items:3)
  end

  def show; end

  def new; end

  def create
    @vehicle.save(validate: false)
    redirect_to vehicle_step_path(@vehicle, :step1)
  end

  def edit
    redirect_to vehicle_step_path(@vehicle, :step1)
  end
  
  def update
    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Vehicle was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    return unless Favorite.where(vehicle_id: @vehicle.id).destroy_all && @vehicle.destroy

    redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.'
  end
  
  def search
    @pagy, @results = pagy(Vehicle.search_results(params[:query_params]), items: 3)
  end
  
  def close
    @vehicle.update(status: 'close') 
    redirect_to vehicles_path, notice: 'Vehicle status has been set to close.'
  end

  def payment
    @vehicle = Vehicle.find(params[:id])
  end

  def process_payment
    @vehicle = Vehicle.find(params[:id])
  
    begin
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken]
      })
  
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @vehicle.price * 100,
        description: "Payment for Vehicle: " + @vehicle.carModel,
        currency: "pkr"
      })
  
      flash[:notice] = 'Payment successful'
      redirect_to @vehicle
  
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to payment_vehicle_path(@vehicle)
    end
  end
  

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def set_current_user 
    @user = current_user
  end 

  def new_vehicle 
  @vehicle = @user.vehicles.new
  end

  def vehicle_params
    params.require(:vehicle).permit(
      :city,
      :mileage,
      :carModel,
      :price,
      :engineType,
      :transmissonType, 
      :engineCapicity, 
      :color, 
      :assemblyType, 
      :description, 
      :primaryContact, 
      :secondaryContact,
      :status,
      vehicle_image: []
    )
  end

end

app/helpers/vehicle/steps_helper.rb
module Vehicle::StepsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_search_result.html.erb
<div class="search-table">
  <% if @results.empty? %>
    <p style=" font-size: 30px; font-weight: bold; text-align: center;">No vehicle found</p>
  <% else %>
  <% @results.each do |vehicle| %>
  <div class="list-container">
    <div class="card">
      <div class="card-body" style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;">
        <% if vehicle.vehicle_image.attached? %>
          <%= image_tag vehicle.vehicle_image.first, size: '100x100' %>
        <% else %>
          <img src="<%= vehicle.vehicle_image %>" class="card-img" alt="Vehicle Image" style="width: 100px; height: 100px; margin-right: 10px;">
        <% end %>
        <div>
          <h5 class="card-title"><%= vehicle.carModel.capitalize %></h5>
          <p class="card-text"><%= vehicle.price %> PKR</p>
          <% if current_user %>
            <% if current_user.favorites.exists?(vehicle_id: vehicle.id) %>
              <%= link_to remove_from_favorites_favourite_path(id: vehicle.id), method: :delete, remote: true do %>
                <i class="bi bi-heart-fill text-danger h3" ></i> 
              <% end %>
            <% else %>
              <%= link_to add_to_favorites_favourite_path(id: vehicle.id), method: :post, remote: true do %>
                <i class="bi bi-heart h3 text-black" ></i> 
              <% end %>
            <% end %>
          <% end %>
          <%= link_to "Show Details", vehicle_path(vehicle), class: "btn btn-primary" %>      
        </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>
<div class="pagy_nav_bootstrap" style="margin-left: 200px; margin-top:30px; margin-bottom:30px;">
 <%= pagy_bootstrap_nav(@pagy).html_safe %>
 </div>

app/views/vehicles/index.html.erb
<div>
  <div class="favorite-title">
    <h1 style="text-align: center;">My Ads</h1>
  </div>
</div>
<% if @vehicles.empty? %> 
  <p style=" font-size: 30px; font-weight: bold; text-align: center;"> You do not have any ad</p>
    <% else %>
<div class="posts">
    <% @vehicles.each do |vehicle| %>
      <div class="list-container">
        <div class="card">
          <div class="card-body" style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;">
            <% if vehicle.vehicle_image.attached? %>
              <%= image_tag vehicle.vehicle_image.first, size: '100x100' %>
            <% else %>
              <img src="<%= vehicle.vehicle_image %>" class="card-img" alt="Vehicle Image" style="width: 100px; height: 100px; margin-right: 10px;">
            <% end %>
            <div>
              <h5 class="card-title"><%= vehicle.carModel.capitalize %></h5>
              <p class="card-text">PKR: <%= vehicle.price %></p>
              <%= link_to 'Edit', edit_vehicle_path(vehicle), class: 'btn btn-primary' %>
              <%= link_to 'Delete', vehicle_path(vehicle), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              <% if vehicle.status == 'open' %>
                <%= link_to 'Close', close_vehicle_path(vehicle), method: :put, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to close this vehicle?' } %>
              <% else %>
                <%= link_to 'Closed', '#', class: 'btn btn-secondary', disabled: true, title: 'This vehicle is already closed' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% end %>
</div>

<div class="pagy_nav_bootstrap" style="margin-left: 650px; margin-top:30px"><%== pagy_bootstrap_nav(@pagy).html_safe %></div>

app/views/vehicles/search.html.erb
<div class="home-container" data-controller="search-form">
  <div>
  <%= form_tag search_vehicles_path, method: :get, id: 'search-form', remote: true do %>
    <div class="row2">
      <%= select_tag "query_params[car_model]", options_for_select(Vehicle.carModels.keys, params.dig('query_params', 'car_model')), prompt: 'Select Car Model' %>
      <%= select_tag "query_params[city]", options_for_select(Vehicle.cities.keys, params.dig('query_params', 'city')), prompt: 'Select City' %>
      <%= select_tag "query_params[price]", options_for_select([["1000000", "price1"], ["2000000", "price2"], ["3000000", "price3"]], params.dig('query_params', 'price')), prompt: 'Select Price Range' %>
    </div>
    <div id="filterRows" class="collapse show">
      <div class="row2">
        <%= select_tag "query_params[engine_type]", options_for_select(Vehicle.engineTypes.keys, params.dig('query_params', 'engine_type')), prompt: 'Engine Details' %>
        <%= select_tag "query_params[transmisson_type]", options_for_select([["manual", "manual"], ["automatic", "automatic"]], params.dig('query_params', 'transmisson_type')), prompt: 'Transmission Type' %>
        <%= select_tag "query_params[color]", options_for_select(Vehicle.colors.keys, params.dig('query_params', 'color')), prompt: 'Color' %>
      </div>
      <div class="row2">
        <%= select_tag "query_params[mileage]", options_for_select([["10", "mileage1"], ["15", "mileage2"], ["20", "mileage3"]], params.dig('query_params', 'mileage')), prompt: 'Select Mileage' %>
        <%= select_tag "query_params[engine_capacity]", options_for_select([["1.0L", "e1"], ["2.0L", "e2"], ["3.0L", "e3"]], params.dig('query_params', 'engine_capacity')), prompt: 'Engine Capacity' %>
        <%= select_tag "query_params[assembly_type]", options_for_select(Vehicle.assemblyTypes.keys, params.dig('query_params', 'assembly_type')), prompt: 'Assembly Type' %>
      </div>
    </div>
    <button type="button" class="btn btn-secondary m-1" data-action="search-form#toggleFilters">Show less</button>
    <div class='d-flex justify-content-end'>
      <%= submit_tag 'Search', class: 'btn btn-primary m-1', data: { turbolinks: false } %>
      <button type="button" class="btn btn-secondary m-1 btn-clear-filters" data-action="search-form#clearFilters">Clear Filters</button>
    </div>
  <% end %>
  
  </div>
<div class="search-table">
 <%= render "search_result" %>
 </div>
</div>

app/views/vehicles/search.js.erb
$('.search-table').html("<%= j render "search_result" %>");

app/views/vehicles/show.html.erb
<div class='vehicle-details'>
  <div class="left">
    <div class="left-wrapper">
      <div class="left-container">
        <div class="favourite-icon">
          <% if current_user %>
            <% if current_user.favorites.exists?(vehicle_id: @vehicle.id) %>
              <%= link_to remove_from_favorites_favourite_path(id: @vehicle.id), method: :delete, remote: true do %>
                <i class="bi bi-heart-fill text-danger h2"></i> 
              <% end %>
            <% else %>
              <%= link_to add_to_favorites_favourite_path(id: @vehicle.id), method: :post, remote: true do %>
                <i class="bi bi-heart h2 text-black"></i> 
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div id="imageCarousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @vehicle.vehicle_image.each_with_index do |image, index| %>
              <li data-target="#imageCarousel" data-slide-to="<%= index %>" <%= index.zero? ? 'class="active"' : '' %>></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% @vehicle.vehicle_image.each_with_index do |image, index| %>
              <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
                <%= image_tag image, size: '450x350', class: 'd-block w-100' %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
            <i class="bi bi-chevron-left h3"></i>
          </a>
          <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
            <i class="bi bi-chevron-right h3"></i>
          </a>
        </div>
      </div>
      <div class="d-flex boxes">
        <div class="box">
          <div class="box-detail">
            <i class="bi bi-fuel-pump-fill h3"></i>
            <p> <%=@vehicle.engineType %></p>
          </div>
        </div>
        <div class="box">
          <div class="box-detail">
            <i class="bi bi-car-front-fill h3"></i>
            <p> <%=@vehicle.carModel.capitalize %></p>
          </div>
        </div>
        <div class="box">
          <div class="box-detail">
            <i class="bi bi-speedometer h3"></i>
            <p> <%=@vehicle.mileage %></p>
          </div>
        </div>
        <div class="box">
          <div class="box-detail">
            <i class="bi bi-gear h3"></i>
            <p> <%=@vehicle.transmissonType %></p>
          </div>
        </div>
        <div class="box">
          <div class="box-detail">
            <i class="bi bi-palette h3"></i>
            <p> <%=@vehicle.color %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="right">
    <div class="right-container">
      <h1 class="mb-5 text-success">PKR:<%= @vehicle.price %> </h1>
      <button
        class="btn btn-primary mb-3 w-100"
        data-controller="vehicles"
        data-action="click->vehicles#showPhoneNumber"
        data-phone-number="<%= @vehicle.primaryContact %>"
        data-target="#phoneModal"
        data-toggle="modal"
      >
        <i class="bi bi-telephone h3"></i> Show Phone
      </button>
      <%= form_tag process_payment_vehicle_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Pay Amount"
          data-amount=<%=@vehicle.price %>
          data-locale="auto">
        </script>
      <% end %>

    </div>
    <div class="right-container1">
      <p class="mb-3 text-primary"> Safety Tips for Transactions</p>
      <p class="mb-3"> 1: Use a safe location to meet seller</p>
      <p class="mb-3"> 2: Avoid cash Transactions</p>
      <p class="mb-3"> 3: Beware Unrealistic Offers</p>
    </div>
  </div>
</div>
<div class="phone-number" style="display: none;"><%= @vehicle.primaryContact %></div>
<div class="modal fade" id="phoneModal" tabindex="-1" role="dialog" aria-labelledby="phoneModalLabel" aria-hidden="true" data-controller="vehicles">  
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="phoneModalLabel">Phone Number</h5>
        <button type="button" id="closeModal" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span id="phoneNumber"></span>
      </div>
      <div class="modal-footer">
        <button type="button" id="close-Modal" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script src="https://checkout.stripe.com/checkout.js"></script>