config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "vehicles#search"
  
  resources :lists, only: [:index, :create]
  resources :payments, only: [:new, :create]
  get 'payment_success', to: 'payments#create', as: 'payment_success'
  get 'payment_cancel', to: 'payments#new', as: 'payment_cancel'

  
  resources :vehicles do 
    resources :steps, only: [:show, :update], controller: 'vehicle/steps'
    collection do
      get 'search'
    end
    member do
      put 'close'
      get 'payment'
      post 'process_payment'
      
    end
  end

  resources :favourites, only: [:index, :create, :destroy] do
    member do
      post 'add_to_favorites'
      delete 'remove_from_favorites'
    end
  end

  namespace :api do
    post :auth, to: "authentication#create"
    delete :auth, to: "authentication#destroy"
    resources :vehicles do 
      resources :steps, only: [:show, :update], controller: 'vehicle/steps'
      collection do
        get 'search'
      end                                                                 
      member do
        put 'close'
      end
    end
  
    resources :favourites, only: [:index, :create, :destroy] do
      member do
        post 'add_to_favorites'
        delete 'remove_from_favorites'
      end
    end
    
  end

end

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
     <% flash.each do |f| %>
   <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    toastr['<%= type %>']('<%= f[1] %>');
  <% end %>
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
          <%= link_to "Favorites", favourites_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "My Ads", vehicles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= button_to "Post Ad", vehicles_path, method: :post, class: 'nav-link' %>
      </li>
      <% end %>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
        <% end %>
      </li>
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Signup", new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carsell</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


  </head>

  <body>
  <%= render "layouts/messages" %>
  <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>